### PR TITLE
Replace sonarqube-api with custom client

### PR DESCRIPTION
**Pull request by awilmore**
Hoping to fix this issue by updating to the latest version of the sonar api package: https://github.com/mx51/msp-dispute-service/actions/runs/5107265135/jobs/9180079068?pr=270

**UPDATE**

Turns out the maintainer for the python-sonarqube-api stuck his project behind a paywall. I added my own client instead, which works for now.

### CODE REVIEW

**Review by aquam8 — APPROVED** [review]

**Comment by awilmore** [comment]
As with all things Sonar, any version change at all breaks something: https://github.com/mx51/docker-reference-app/actions/runs/5107482015/jobs/9180418602?pr=14

Still working on it.

**Comment by awilmore** [comment]
Replaced the sonarqube-api code with a custom client, which seems to work: https://github.com/mx51/docker-reference-app/actions/runs/5108020436/jobs/9181455133?pr=14#step:7:52

**Review by tony-assembly — APPROVED** [review]
🙏

**Review by aquam8 — APPROVED** [review]
thank you Adam!

**Pull request merged**
